### PR TITLE
Garmin backfill

### LINKED ISSUE #3: Add Backfill service for Garmin historic data
Add backfill summary service implementation (possibly storing offsets in Redis with locking).

### PR DESCRIPTION
**Pull request by yatharthranjan**
Backfill Implementation for getting historic Garmin data with offsets and locking in Redis. Offset related code is taken from the radar-output app and adapted for this application (for eg- Topic + Partition is replaced with UserId + Route).

~We still need to decide how to specify the end date for backfill collection.
Currently, it can be defined in the config for each user and a default end date if it is not configured for the user. But I think a better place for it would be rest-source-auth. Even exposing the create date of the subject in authoriser can be used as end date for backfill. But would be good to have explicit start and end date keys for backfill for flexibility. What are your thoughts @blootsvoets, @nivemaham, @mpgxvii and @afolarin ?~

As discussed below the end date for backfill will be taken from the createDate for the subject in authorizer.

Closes #3

Ps: Ignore the CI test as they will be fixed by #5

### CODE REVIEW

**Comment by nivemaham** [comment]
The rest-source-auth already supports a start date and end date per user. Can't you use the REST APIs to get that information and use it for the back-filling purpose?

**Comment by yatharthranjan** [comment]
Hi @nivemaham, yes it supports end date but we need 2 end dates here (1 to stop historic collection when the user has authorised since we will receive push data from that point on and another one to deregister user when the final end date is reached so we stop receiving push data from Garmin).

**Comment by nivemaham** [comment]
Maybe I am not understanding the whole work-flow. In general you want to have a start-date and an end-date for data collection. And that is the period you want to collect data in all cases. Whether it is back-fill or not. 
Whether it is historic(I am assuming you go back time from now to collect data) or real-time, the local state should be managed by the app. Isn't it?
Let's say if the start date is earlier than now, the connector automatically goes back in time to collect that data. I would expect the same here as well. 
At least, I am not getting the message how this can be explained to the researcher/end user who will be recruiting participants? 
We want to keep the UI/workflow simple and straight forward for on-boarding. Having two end-dates sounds confusing to me and I am still struggling to see the purpose/difference. 
Lastly, of course adding another end-date is possible for rest-source-auth. But we need to have a harmonized concept across the sources.

**Comment by yatharthranjan** [comment]
Ok, sorry for not explaining it clearly. So, with Garmin, the workflow is following (for push integration) - 

1. The user authorizes their Garmin Account with our app. 
2. Garmin automatically starts sending realtime POST requests to our endpoint with data of that user from that point on.
3. We still don't get the historic data (before the user authorized).
4. So we need to send Backfill requests to Garmin Server for those.
5. We need a way to specify till when to request the Backfill (which will be the date the user authorized). 
6. If we use the end date of data collection we will have duplicate data sent by Garmin (from when the user authorized to the end date for the user). To avoid this duplicate data, we need a way of knowing when the user authorized so we can stop the backfill requests (as data past that point is already sent in realtime by Garmin)

So, we actually don't need to expose this to the researcher if it will be confusing. We can just expose the createDate for the subject in rest-sources-auth as that will be the date they authorised.

**Comment by blootsvoets** [comment]
Adding a `created` timestamp to the rest source authorizer seems like a good general purpose improvement.

**Review by blootsvoets — APPROVED** [review]
Lgtm

**Pull request merged**
